#!/bin/bash
# record-gate-run.sh — Append-only telemetry writer for the spec pipeline.
# The Verifier calls this once per completed pipeline run (spec 012); the record
# lands as one JSON object per line in an append-only runs.jsonl that is tracked
# in git — the trend is the point, it survives merges and feeds the weekly view
# (scripts/gate-stats.sh).
#
# Usage:
#   record-gate-run.sh -record '<json>' [-f <file>]
#   echo '<json>' | record-gate-run.sh [-f <file>]
#
# Default file: <repo-root>/runs.jsonl. -f or the GATE_RUNS_FILE env var
# overrides it. The record is appended with `>>` (append-only: never rewritten,
# no dedup, no sort).
#
# Record schema (all keys required except runId, loopCount, phase1Retries,
# phase2Retries, which default — runId is generated by this script via uuidgen
# falling back to <epoch-nanos>-<pid>; the loop/retry fields default from
# SPEC_LOOP_COUNT / SPEC_PHASE1_RETRIES / SPEC_PHASE2_RETRIES, then to 0):
#   { "runId": "uuid", "specSlug": "012-slug" | "jiraKey": "PROJ-123",  // XOR, exactly one
#     "gatesFailed": ["design-principles"], "loopCount": 2,
#     "phase1Retries": 1, "phase2Retries": 0, "warnings": ["..."],
#     "durationSec": 123.4, "outcome": "pass" | "fail" | "block" }
#
# Validation (no jq — must not add it as a hard dependency): the record must be
# a single line with balanced braces, must contain each required key name,
# `outcome` must be one of pass|fail|block, and exactly one of specSlug/jiraKey
# must be present. Violations → stderr message naming the field, exit 1,
# nothing appended.
#
# Exit codes:
#   0 — record validated and appended
#   1 — validation failure (nothing appended)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="${GATE_RUNS_FILE:-$ROOT/runs.jsonl}"
RECORD=""

while [ $# -gt 0 ]; do
  case "$1" in
    -record)
      RECORD="${2:-}"
      [ -n "$RECORD" ] || { echo "record-gate-run: -record requires a JSON record (or pipe it on stdin)" >&2; exit 1; }
      shift 2 ;;
    -f)
      FILE="${2:-}"
      [ -n "$FILE" ] || { echo "record-gate-run: -f requires a file path" >&2; exit 1; }
      shift 2 ;;
    *) echo "record-gate-run: unknown option: $1" >&2; exit 1 ;;
  esac
done

# If no -record argument was given, read the record from stdin (never block on
# an interactive terminal).
if [ -z "$RECORD" ]; then
  if [ -t 0 ]; then
    echo "record-gate-run: no record provided (use -record '<json>' or pipe on stdin)" >&2
    exit 1
  fi
  RECORD="$(cat 2>/dev/null || true)"
fi

# Trim surrounding whitespace/newlines so a piped record with a trailing LF
# still validates as a single line.
RECORD="$(printf '%s' "$RECORD" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"

# ── Validation (jq-free, shallow by design) ──────────────────────────────────
err() { echo "record-gate-run: invalid record: $1" >&2; exit 1; }

case "$RECORD" in
  *$'\n'*) err "record must be a single line" ;;
esac

ob=$(printf '%s' "$RECORD" | tr -cd '{' | wc -c | tr -d ' ')
cb=$(printf '%s' "$RECORD" | tr -cd '}' | wc -c | tr -d ' ')
case "$RECORD" in
  '{'*) ;;
  *) err "record must be a JSON object starting with '{'" ;;
esac
case "$RECORD" in
  *'}') ;;
  *) err "record must be a JSON object ending with '}'" ;;
esac
[ "$ob" -eq "$cb" ] || err "unbalanced braces ($ob '{' vs $cb '}')"

# Required keys: everything in the schema except runId / loopCount /
# phase1Retries / phase2Retries, which default (generated / from SPEC_* env,
# then 0) and are injected below.
for key in gatesFailed warnings durationSec outcome; do
  printf '%s' "$RECORD" | grep -q "\"$key\"" || err "missing required field '$key'"
done

outcome="$(printf '%s' "$RECORD" | sed -n 's/.*"outcome"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
case "$outcome" in
  pass|fail|block) ;;
  *) err "'outcome' must be one of pass|fail|block (got '${outcome:-<missing>}')" ;;
esac

# grep -o exits 1 on no match; with pipefail that would abort the whole script
# under set -e — `|| true` keeps the count assignments safe.
has_slug=$(printf '%s' "$RECORD" | grep -o '"specSlug"' | wc -l | tr -d ' ' || true)
has_jira=$(printf '%s' "$RECORD" | grep -o '"jiraKey"' | wc -l | tr -d ' ' || true)
if [ "$((has_slug + has_jira))" -ne 1 ]; then
  err "exactly one of 'specSlug' or 'jiraKey' must be present (got $has_slug specSlug, $has_jira jiraKey)"
fi

# ── Defaults ─────────────────────────────────────────────────────────────────
# runId: generated by the script when the record omits it.
if ! printf '%s' "$RECORD" | grep -q '"runId"'; then
  run_id="$(uuidgen 2>/dev/null || printf '%s-%s' "$(date +%s%N 2>/dev/null || date +%s)" "$$")"
  [ -n "$run_id" ] || run_id="$(date +%s)-$$"
  RECORD="${RECORD%\}},\"runId\":\"${run_id}\"}"
fi

# loopCount/phase1Retries/phase2Retries: default from the orchestrator's
# SPEC_* env vars (spec 008 budget audit trail), then to 0.
inject_count() {
  local key="$1" envval="$2" val
  val="${envval:-0}"
  printf '%s' "$RECORD" | grep -q "\"$key\"" && return 0
  case "$val" in
    *[!0-9]*) val=0 ;;
  esac
  RECORD="${RECORD%\}},\"${key}\":${val}}"
}
inject_count loopCount "${SPEC_LOOP_COUNT:-}"
inject_count phase1Retries "${SPEC_PHASE1_RETRIES:-}"
inject_count phase2Retries "${SPEC_PHASE2_RETRIES:-}"

# ── Append (append-only; never touches the file on validation failure) ───────
printf '%s\n' "$RECORD" >> "$FILE"
echo "record-gate-run: appended record to $FILE" >&2
